openapi: 3.0.4
info:
  title: Messenger log models
  description: Models for logging services
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.0

paths: {}

components:
  schemas:
    CommonLogModel:
      title: Общая модель лога
      description: Общая модель лога для всех микросервисов системы
      type: object
      properties:
        messageTime:
          type: string
        logId:
          type: string
        source:
          type: string
        chat:
          $ref: '#/components/schemas/ChatLogModel'
        errors:
          type: array
          items:
            $ref: '#/components/schemas/ErrorLogModel'

    ChatLogOperation:
      type: string
      enum:
        - create
        - read
        - update
        - delete
        - search
        - init
        - finish

    ChatLogModel:
      title: Модель лога для микросервиса Messenger
      type: object
      properties:
        requestId:
          type: string
        operation:
          $ref: '#/components/schemas/ChatLogOperation'
        requestChat:
          $ref: '#/components/schemas/ChatLog'
        requestSearch:
          $ref: '#/components/schemas/ChatSearchLog'
        responseChat:
          $ref: '#/components/schemas/ChatLog'
        responseChats:
          type: array
          items:
            $ref: '#/components/schemas/ChatLog'

    ErrorLogModel:
      title: Модель лога для ошибки
      type: object
      properties:
        message:
          type: string
        field:
          type: string
        code:
          type: string
        level:
          type: string

    ChatLog:
      title: chat log model
      type: object
      properties:
        chatId:
          type: string
        title:
          type: string
        description:
          type: string
        type:
          type: string
        mode:
          type: string
        owner_id:
          type: string
        participants:
          type: array
          uniqueItems: true
          items:
            type: string
        metadata:
          type: string
          format: json

    ChatSearchLog:
      title: log model for filter request
      properties:
        searchFields:
          type: string

    ChatUpdateLog:
      title: log model for update request
      properties:
        updateFieldName:
          type: string
